---
title: "MiscCleaning"
---

Downloading libraries
```{r}
library(tidyverse)
library(readxl)
library(janitor)
```


Getting generic ballot results
```{r}
senate_results <- read.csv("../data/1976-2020-senate.csv")
house_results <- read.csv("../data/1976-2022-house.csv")

unopposed_prop <- 0.71 #The average % of the vote 
                        #an unopposed candidate would have received, had they been opposed

contested_party_summaries <- house_results %>%
  filter(totalvotes > 1, party %in% c("DEMOCRAT", "REPUBLICAN")) %>%
  group_by(year, party) %>%
  summarize(total_party_votes = sum(candidatevotes), .groups = "keep")

contested_total_summaries <- house_results %>%
  filter(totalvotes > 1, party %in% c("DEMOCRAT", "REPUBLICAN")) %>%
  group_by(year) %>%
  summarize(mean_votes = mean(totalvotes))

uncontested_party_summaries <- house_results %>%
  filter(totalvotes <= 1, party %in% c("DEMOCRAT", "REPUBLICAN")) %>%
  group_by(year, party) %>%
  summarize(party_uncontested = n(), .groups = "keep")

uncontested_total_summaries <-  house_results %>%
  filter(totalvotes <= 1, party %in% c("DEMOCRAT", "REPUBLICAN")) %>%
  group_by(year) %>%
  summarize(total_uncontested = n())

generic_ballot <- contested_party_summaries %>%
  full_join(contested_total_summaries, by = "year") %>%
  full_join(uncontested_party_summaries, by = c("year", "party")) %>%
  full_join(uncontested_total_summaries, by = "year") %>%
  mutate(party_uncontested = replace_na(party_uncontested, 0)) %>%
  mutate(opposite_uncontested = total_uncontested - party_uncontested) %>%
  mutate(modeled_vote = total_party_votes +
           (party_uncontested * mean_votes * unopposed_prop) +
           (opposite_uncontested * mean_votes * (1 - unopposed_prop))) %>%
  select(year, party, modeled_vote) %>%
  pivot_wider(names_from = "party",
              values_from = "modeled_vote") %>%
  mutate(pct_margin = (DEMOCRAT - REPUBLICAN) / (DEMOCRAT + REPUBLICAN) * 100) %>%
  select(year, pct_margin) %>%
  write_csv("../cleaned_data/generic_ballot.csv")
```


Cleaning the COVI database, and getting important results from each state and year
```{r}
covi_2000 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2000")
covi_2004 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2004")
covi_2008 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2008")
covi_2012 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2012")
covi_2016 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2016")
covi_2020 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2020")
covi_2022 <- read_excel("../data/Master 1996 2022 Election voting requirements.xlsx", 
                        sheet = "2022")
#list of variables to keep
vars <- c("State.y", "Year", "AbsenteeExcuseReq", "PollHours", "AvgPollHours", "MaxPollHours","MinPollHours", "Issue Area #1-Registration Deadlines", "VoterIDLaws", "NoVoterID", "NoAllMailVote", "NoEarlyVote", "NoFelonReg", "NoFelonsRegAfterIncar", 
          "nonstrictID", "nonstrictPhoto", "NOonlineregistration", "NoPermanentAbsentee", 
          "NoPollPlaceReg", "NoPR", "NoSameDayReg", "nostateholiday", 
         "PR16", "PR17", "PR175", "PR60", "PR90", "strictID", "strictPhoto")

state_numbers <- covi_2000 %>%
  select(statenu, State)

full_covi <- bind_rows(covi_2000, covi_2004, covi_2008, covi_2012, covi_2016,
                       covi_2020, covi_2022) %>%
  mutate(NoFelonReg = ifelse(is.na(NoFelonReg), NoFelonsReg, NoFelonReg), 
         NoAllMailVote = ifelse(is.na(NoAllMailVote), noallmailvoting, NoAllMailVote), 
         NoVoterID = ifelse(is.na(NoVoterID), NovoterID, NoVoterID),
         MaxPollHours = ifelse(is.na(MaxPollHours), PollHoursMax, MaxPollHours),
         MinPollHours = ifelse(is.na(MinPollHours), PollHoursMin, MinPollHours),
         AvgPollHours = ifelse(is.na(AvgPollHours), PollHrsAvg, AvgPollHours),
         VoterIDLaws = ifelse(is.na(`Issue Area #5-Voter ID Laws`), `Issue Area #7-Voter ID Laws`, 
                              `Issue Area #5-Voter ID Laws`),
         PollHours = ifelse(is.na(`Issue Area #6-Poll Hours`), `Issue Area #8-Poll Hours`,
                            `Issue Area #6-Poll Hours`),
         .keep = "unused") %>%
  full_join(state_numbers, by = "statenu") %>%
  select(all_of(vars)) %>%
  rename(regdeadlines = `Issue Area #1-Registration Deadlines`, 
         State = State.y) %>%
  rename_with(tolower)

write.csv(full_covi, "../cleaned_data/cost_of_voting.csv")

```

