name: Run Model

on:
  workflow_run:
    workflows: ["Update Model"]
    branches: [main]
    types: 
      - completed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ELECTIONMODELKEY }}

      - name: Install git-crypt
        run: |
          git clone https://github.com/AGWA/git-crypt.git
          cd git-crypt && make && make install PREFIX=/opt/project
          echo "/opt/project/bin" >> $GITHUB_PATH
  
      - name: Unlock git-crypt
        run: |
          echo ${{ secrets.GIT_CRYPT_KEY }} | base64  -d > ./git-crypt-key
          git-crypt unlock ./git-crypt-key
          rm ./git-crypt-key

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git-crypt

      - name: Run the script
        run: |
          python code/ModelPredicting.py --all

      - name: Commit and push if there are changes
        run: |
          git-crypt lock
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git pull
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"
          git push https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.ELECTIONMODELKEY }}@github.com/BPR-Data-Team/ElectionModel2024.git