name: Update Model

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC / 20:00 EDT
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ELECTIONMODELKEY }}

      - name: Install & unlock git-crypt
        run: |
          if ! command -v git-crypt &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y git-crypt
          fi
          echo "${{ secrets.GIT_CRYPT_KEY }}" | base64  -d > ./production.env.key
          git-crypt unlock ./production.env.key
          rm ./production.env.key
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'
  
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          dependencies: '"hard"'
          packages: |
            any::tidyverse
            any::tidycensus
            any::meta

      # - name: List installed packages
      #   run: Rscript -e "print(installed.packages()[, c('Package', 'LibPath')])"

      - name: Config Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git pull

      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2

      - name: Run the script
        env: 
            FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
            CENSUS_API_KEY: ${{ secrets.CENSUS_API }}
        run: |
          python code/data_fetcher.py --all
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"
          Rscript code/ContinuousCleaning/CensusDemographics.R
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model" 
          Rscript code/ContinuousCleaning/Fundamentals.R
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"
          Rscript code/ContinuousCleaning/FEC.R
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"
          python code/ContinuousCleaning/PollingAverages.py --all
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"
          Rscript code/ContinuousCleaning/CombiningData.R
          git add .
          git diff-index --quiet HEAD || git commit -m "Update model"

      - name: Encrypt files and push
        run: |
          git-crypt lock
          git diff-index --quiet HEAD || git commit -m "Update model"
          git push https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.ELECTIONMODELKEY }}@github.com/BPR-Data-Team/ElectionModel2024.git
